// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubshntkfzkptcworxtdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVic2hudGtmemtwdGN3b3J4dGRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDE5OTIsImV4cCI6MjA2NTMxNzk5Mn0.3HBoofYDZWaWkIX02QU_zjC-T7NTE1vHW_YhV0Tu_o4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);